---
apiVersion: v1
kind: Service
metadata:
  name: myetcd-client
spec:
  type: ClusterIP
  ports:
  - name: myetcd-client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: myetcd
---
apiVersion: v1
kind: Service
metadata:
  name: myetcd
spec:
  clusterIP: None
  ports:
  - port: 2379
    name: client
  - port: 2380
    name: peer
  selector:
    app: myetcd
---

